// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */
//
// import model from './model2.glb';
// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'
// import { useFrame } from "@react-three/fiber";
//
// export function Model(props) {
//   const { nodes, materials } = useGLTF(model)
//     const ref = useRef();
//
//     useFrame((state) => {
//         const t = state.clock.getElapsedTime();
//         if (ref.current) {
//             ref.current.rotation.x = Math.cos(t / 4) / 8;
//             ref.current.rotation.y = (1 + Math.sin(t / 1.5)) / 10;
//         }
//     });
//
//   return (
//     <group {...props} dispose={null} ref={ref} receiveShadow={true}>
//       <primitive object={nodes.Hips} />
//       <skinnedMesh receiveShadow={true} castShadow={true} geometry={nodes.Wolf3D_Body.geometry} material={materials.Wolf3D_Body} skeleton={nodes.Wolf3D_Body.skeleton} />
//       <skinnedMesh receiveShadow={true} castShadow={true} geometry={nodes.Wolf3D_Hair.geometry} material={materials.Wolf3D_Hair} skeleton={nodes.Wolf3D_Hair.skeleton} />
//       <skinnedMesh receiveShadow={true} castShadow={true} geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={materials.Wolf3D_Outfit_Bottom} skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton} />
//       <skinnedMesh receiveShadow={true} castShadow={true} geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={materials.Wolf3D_Outfit_Footwear} skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton} />
//       <skinnedMesh receiveShadow={true} castShadow={true} geometry={nodes.Wolf3D_Outfit_Top.geometry} material={materials.Wolf3D_Outfit_Top} skeleton={nodes.Wolf3D_Outfit_Top.skeleton} />
//       <skinnedMesh receiveShadow={true} castShadow={true} name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeLeft.skeleton} morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences} />
//       <skinnedMesh receiveShadow={true} castShadow={true} name="EyeRight" geometry={nodes.EyeRight.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeRight.skeleton} morphTargetDictionary={nodes.EyeRight.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight.morphTargetInfluences} />
//       <skinnedMesh receiveShadow={true} castShadow={true} name="Wolf3D_Head" geometry={nodes.Wolf3D_Head.geometry} material={materials.Wolf3D_Skin} skeleton={nodes.Wolf3D_Head.skeleton} morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences} />
//       <skinnedMesh receiveShadow={true} castShadow={true} name="Wolf3D_Teeth" geometry={nodes.Wolf3D_Teeth.geometry} material={materials.Wolf3D_Teeth} skeleton={nodes.Wolf3D_Teeth.skeleton} morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences} />
//     </group>
//   )
// }
//
// useGLTF.preload(model)
